osx_image: xcode8.3
language: objective-c
cache:
  - bundler
  - cocoapods

podfile: Example/Podfile

before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example --repo-update

script:
- set -o pipefail && xcodebuild build test -workspace Example/DigitsMigrationHelper.xcworkspace -scheme DigitsMigrationHelper-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO | xcpretty
- pod lib lint DigitsMigrationHelper.podspec --allow-warnings
